export const mockJobListings = [
  {
    id: 1,
    title: 'Registered Nurse',
    department: 'Nursing',
    location: 'Jacksonville (Duval, Clay, St. Johns, Nassau, Baker)',
    type: 'Full-time',
    description: 'We are seeking a compassionate and skilled Registered Nurse to join our team...',
    requirements: [
      'Valid RN license in the state of Florida',
      'Minimum of 2 years of experience in home health care',
      'Strong communication and interpersonal skills',
      'Ability to work independently and as part of a team',
    ],
  },
  {
    id: 2,
    title: 'Physical Therapist',
    department: 'Therapy',
    location: 'Palm Coast (Flagler, Volusia)',
    type: 'Full-time',
    description: 'Join our therapy team as a Physical Therapist and help patients regain their mobility...',
    requirements: [
      'Licensed Physical Therapist in the state of Florida',
      'Minimum of 3 years of experience in home health care',
      'Experience with geriatric patients',
      'Excellent documentation skills',
    ],
  },
  {
    id: 3,
    title: 'Occupational Therapist',
    department: 'Therapy',
    location: 'West Palm Beach (Palm Beach)',
    type: 'Part-time',
    description: 'We are looking for an experienced Occupational Therapist to provide in-home therapy services...',
    requirements: [
      'Licensed Occupational Therapist in the state of Florida',
      'Minimum of 2 years of experience in home health care',
      'Knowledge of adaptive equipment and home modification techniques',
      'Strong problem-solving skills',
    ],
  },
  {
    id: 4,
    title: 'Home Health Aide',
    department: 'Patient Care',
    location: 'Hallandale (Broward)',
    type: 'Full-time',
    description: 'Join our team as a Home Health Aide and provide essential care to patients in their homes...',
    requirements: [
      'Certified Home Health Aide',
      'Minimum of 1 year of experience in home health care',
      'Valid driver\'s license and reliable transportation',
      'Compassionate and patient-centered approach to care',
    ],
  },
  {
    id: 5,
    title: 'Speech-Language Pathologist',
    department: 'Therapy',
    location: 'Aventura (Miami-Dade)',
    type: 'Full-time',
    description: 'We are seeking a qualified Speech-Language Pathologist to provide therapy services to our patients...',
    requirements: [
      'Licensed Speech-Language Pathologist in the state of Florida',
      'Minimum of 2 years of experience in home health care',
      'Experience with swallowing disorders and cognitive rehabilitation',
      'Excellent documentation and time management skills',
    ],
  },
];